name: Build and Download Artifact

on:
  workflow_dispatch: # Trigger workflow manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Create Artifact
      run: |
        echo "Artifact Content" > artifact.txt

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: artifact.txt

  download:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: artifact
        path: ./downloaded_artifact
