name: Auto Release on Push to Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate zip file
        run: |
          mkdir -p output
          echo "Sample content" > output/sample.txt
          zip -r filename.zip output/

      - name: Generate Version Tag
        id: generate_tag
        run: |
          VERSION="v$(date +'%Y.%m.%d-%H%M%S')"
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Create Git Tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ env.version }}
          git push origin ${{ env.version }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          release_name: "Release ${{ env.version }}"
          body: "Automatic release for version ${{ env.version }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./filename.zip
          asset_name: filename.zip
          asset_content_type: application/zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./filename.zip

  download:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: ./downloaded_files

      - name: List files in the downloaded directory
        run: ls -l ./downloaded_files

  download_release:
    runs-on: windows-latest
    steps:
      - name: Download Release Asset Using PowerShell
        run: |
          $versionTag = "v2024.11.12-043105"
          $repo = "JebaShinba/Build"
          $downloadPath = "C:\\Users\\jebas\\Build\\downloaded_filename.zip"
          $downloadDir = [System.IO.Path]::GetDirectoryName($downloadPath)

          if (!(Test-Path -Path $downloadDir)) {
              New-Item -ItemType Directory -Path $downloadDir | Out-Null
          }

          $response = Invoke-RestMethod -Uri "https://api.github.com/repos/$repo/releases/tags/$versionTag" -UseBasicParsing
          $downloadUrl = ($response.assets | Where-Object { $_.name -eq "filename.zip" }).browser_download_url

          if ($downloadUrl) {
              Invoke-WebRequest -Uri $downloadUrl -OutFile $downloadPath
              Write-Output "Downloaded file saved as $downloadPath."
          } else {
              Write-Output "No asset named 'filename.zip' was found."
          }

      - name: Upload downloaded file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: downloaded_filename.zip
          path: C:\Users\jebas\Build\downloaded_filename.zip
