name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Docker version
        run: docker --version
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/jebashinba/my-image:latest   

      - name: Checkout repository
        uses: actions/checkout@v3
    
        # Set up Python (since we're using Python for Selenium)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: 3.9  # Specify your Python version
    
        # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
    
        # Run the Selenium tests via the shell script
      - name: Run Selenium tests
        run: |
            bash ./run.sh  # Make sure the script is executable