name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Docker version
        run: docker --version
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/jebashinba/my-image:latest   

      - name: Run tests in Docker container
        run: |
          docker run --rm ghcr.io/jebashinba/my-image:latest
          # Start Docker container using the image built with Docker Compose
          docker-compose -f docker-compose.yml up -d

          # Run Selenium tests using docker exec or a testing framework
          docker exec -t my-container-name python -m unittest discover -s tests/test_example.py  # Example: Running Python tests inside the container

          # Optionally, wait for tests to finish, or log the output
          docker logs my-container-name  # This shows logs to check test results

          # Shut down Docker containers after the tests are done
          docker-compose -f docker-compose.yml down

