name: Download Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to download"
        required: true
        default: "v2024.11.18-093216"

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: |
        sudo apt update
        sudo apt install gh -y

    - name: Authenticate GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "${GITHUB_TOKEN}" | gh auth login --with-token

    - name: Download Release
      run: |
        gh release download ${{ github.event.inputs.tag }} --repo JebaShinba/Build --dir "./downloaded_release"
