name: Download Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to download"
        required: true
        default: "v2024.11.18-093216"

jobs:
  download:
    runs-on: windows-latest

    steps:
    - name: Install GitHub CLI
      run: |
        Invoke-WebRequest -Uri https://github.com/cli/cli/releases/latest/download/gh_2.39.0_windows_amd64.msi -OutFile gh-cli.msi
        Start-Process msiexec.exe -Wait -ArgumentList '/i gh-cli.msi /quiet /norestart'
        Remove-Item gh-cli.msi

    - name: Authenticate GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Download Release Assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir "C:\Users\jebas"
        gh release download ${{ github.event.inputs.tag }} \
          --repo JebaShinba/Build \
          --pattern "*.zip" \
          --dir "C:\Users\jebas"

    - name: List Downloaded Files
      run: |
        dir "C:\Users\jebas"
