name: Download Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to download"
        required: true
        default: "v2024.11.18-093216"

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Install GitHub CLI
      run: |
        sudo apt update
        sudo apt install gh -y

    - name: Download Release Assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release download ${{ github.event.inputs.tag }} --repo JebaShinba/Build --pattern "*.zip" --dir "D:\\"

    - name: List Downloaded Files
      run: |
        ls -lah ./downloaded_release
