name: Download Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to download"
        required: true
        default: "v2024.11.18-093216"

jobs:
  download:
    runs-on: windows-latest

    steps:
    - name: Install GitHub CLI
      run: |
        winget install --id GitHub.cli

    - name: Authenticate GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Download Release Assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Ensure the directory exists
        mkdir "C:\Users\jebas\releases"
        
        # Download assets to the specified directory
        gh release download ${{ github.event.inputs.tag }} \
          --repo JebaShinba/Build \
          --pattern "*.zip" \
          --dir "C:\Users\jebas\releases"

    - name: List Downloaded Files
      run: |
        dir "C:\Users\jebas\releases"

