name: Download Release

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  download-release:
    runs-on: [self-hosted, windows]  # Use 'self-hosted' and 'windows' for Windows-based self-hosted runners.

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run bash script
      run: |
        # Use Git Bash to execute the bash script
        C:/Program\ Files/Git/usr/bin/bash.exe C:/Users/shinba/build/test.sh
